### ISSUE TITLE
February Tuesday 6 meetup

### ISSUE THREAD

**Issue by olleolleolle** [malmorb/malmorb.github.com#12]
(This is a planning Issue for a meet-up. It will be updated with information as it gets decided.)

**Date and time**: Tuesday, **February 6**, time: we'll meet and greet at 17:30. (Following the standard formula for a two-talk event.)

- 17.30-17.45 – Meet & Greet
- 17.45-18.30 – Presentation - 
- 18.30-19.00 - Break with pizza
- 19.00-20:00 - Discussions/ 2nd presentation

**Venue**: [Foo Café](http://foocafe.org/) - at Media Evolution City in Malmö - [Location on a map](http://foocafe.org/malmoe/location)

**Sign-up page**: http://www.foocafe.org/malmoe/events/1768-creative-coding-documentation 

**Language:** English

---

Theme: Creative Coding - and documentation

---

# Speaker slots which are agreed

## game developer Bobbi A. Sand on creativity, creative process

> From possible to playable

## documentation enthusiast Olle Jonsson on YARD

Olle will, together with you, add documentation to a popular project which has not-great-yet documentation, using the YARD system. A learning tour!

**Comment by lonroth** [comment]
@olleolleolle I'll be back in Sweden on the 6th so hope to be able to join this meetup.

**Comment by olleolleolle** [comment]
Last meetup, the Discussion part was unstructured and long, and quite productive - many ideas were shared and noted and discussed - this may be hard to fit into a Bigger Format (> 10 participants).

**Comment by olleolleolle** [comment]
And, we have a sign-up page!

**Comment by olleolleolle** [comment]
Thanks for coming, all, it was great.
