### ISSUE TITLE
Malmö.rb Meet-up, August 2017

### ISSUE THREAD

**Issue by olleolleolle** [malmorb/malmorb.github.com#5]
(This is a planning Issue for a meet-up. It will be updated with information as it gets decided.)

**Date and time**: __day, August __, time: TBD

**Venue**: 

> TBD

---

We need to find and decide upon:

- [ ] What type of event: (e.g. "talks and presentations")
- [ ] a venue
- [ ] a date
- [ ] food/drink/snacks?

**Comment by olleolleolle** [comment]
Format idea from Sthlm.rb participant:

>  If it’s people who haven’t met in a long time (or at all), have a format that’s suited to being social, like Open Spaces, where participants put up the topics they’d like to talk about in some corner of the place.

**Comment by jensnockert** [comment]
I'd like to talk about Helix and writing Ruby extensions in Rust with people!

**Comment by olleolleolle** [comment]
Well - this old Issue didn't perform ALL of its duties, but some of it is good, and I'll keep the form.

**Comment by olleolleolle** [comment]
Closing!
