### ISSUE TITLE
Ruby-using companies in Malmö on the front-page

### ISSUE THREAD

**Issue by olleolleolle** [malmorb/malmorb.github.com#7]
I saw Copenhagen.rb having company names under the heading "We use Ruby": http://www.copenhagenrb.dk/

I want that for Malmö!

Do you agree with this idea? Any suggestions on how?

**Comment by tilljoel** [comment]
Agree, here are the ones I know of

- http://www.arthro.ai
- http://protetiko.com
- http://www.herogaming.com
- https://www.axis.com
- http://ranktrail.com
- http://castle.io

Could we ping people on Slack and the Mailing list and ask for some more suggestions?

**Comment by olleolleolle** [comment]
Contacted Michael Tiberg, and we got me some names!

- Upptec - https://upptec.se/
- Trialbee - https://trialbee.com/
- Foo Café - http://foocafe.org/
- Qgroup - http://qgroup.se/
- Jayway - https://www.jayway.com/

**Comment by olleolleolle** [comment]
OK, this is now merged and published.

**Comment by lonroth** [comment]
@olleolleolle Lägg gärna till https://www.mokini.com också. Vi kör så klart Ruby :)

**Comment by olleolleolle** [comment]
@lonroth Do you want to make a PR?

**Comment by lonroth** [comment]
@olleolleolle Sure :)

**Comment by lonroth** [comment]
@olleolleolle Trying to push my feature branch but get access denied?

**Comment by olleolleolle** [comment]
@lonroth Can you fork?
