### ISSUE TITLE
Malmö.rb January 9 meetup

### ISSUE THREAD

**Issue by jensnockert** [malmorb/malmorb.github.com#9]
(This is a planning Issue for a meet-up. It will be updated with information as it gets decided.)

**Date and time**: Tuesday, **January 9**, time: we'll meet and greet at 17:30. (Following the standard formula for a two-talk event. )

**Venue**: [Foo Café](http://foocafe.org/) - at Media Evolution City in Malmö - [Location on a map](http://foocafe.org/malmoe/location)

**Signup:** http://foocafe.org/malmoe/events/1662-ruby-standard-libraries

### Timeline of event

- 17.30-17.45 – Meet & Greet
- 17.45-18.30 – Jens Nockert and Steven Baker each present their favorite Standard Library finds
- 18.30-19.00 - Break with a pizza snack
- 19.00-20:00 - Another activity

### Blurb

Beyond the festive season we will meet again and explore Ruby together! On Tuesday January 9, we will have a meeting, and you are welcome.

The theme is about Ruby's standard library, the code that's always available with Ruby.

_What comes in the box?_ RubyGems are great and all, but what comes along WITH Ruby? This time, we'll take a guided tour of Ruby's Standard Libraries, pausing to look at the weird, the strange and the useful.

There will be short presentations, there will be group activities, there will be time for social breaks.

I hope you bring yourself, your pal, and your curiosity to meet the rest of us on January 9.

---

We need to find and decide upon:

- [ ] What type of event: "talks and presentations", "workshop", "social event"
- [x] a venue
- [x] a date
- [ ] pass the titles and description of the event on to FooCafe
---

# Presentations

## (example) Foo Barsby, on _BazQuux_

Lorem ipsum detailum the talkum.

# Practical help

To be the welcoming face, the figurehead, is _one_ task. There are many small tasks which need to get done, as well.  

- Count the number of participants, for our records
- Keep time of presenters fairly and clearly (*mouthing the words* "You have 5 *shows five fingers* minutes left")
- Update the website malmorb.se with the titles of the talks and archive the old talk to its own page with a link

**Comment by olleolleolle** [comment]
I had some good feedback from a participant:

- Something about gems we like - "The gems of your Gemfile" - pitch gems we like especially much
- How best to use Rubocop
- Generally: Linting done best

**Comment by olleolleolle** [comment]
I have gotten a promise of a lightning talk on the theme "A standard library that I still use and like"

**Comment by lonroth** [comment]
@olleolleolle I believe that topic is a great one and very practical too most of the times.

**Comment by olleolleolle** [comment]
We're still open for the latter activity slot of this event, so anyone wanting to run an activity there, step up to the plate.
